### ISSUE TITLE
Allow mapping arbitrary template names to Schema.org types

### ISSUE THREAD

**Issue by johnfraney** [blurry-dev/blurry#5]
There may be times where Schema.org types aren't specific enough to accommodate every use case. For example, Blurry's own docs use a non-standard Schema type of `ContextWebPage` for its [Templates: context page](https://blurry-docs.netlify.app/templates/context/).

One option is to allow mapping templates types to Schema.org types, possibly in `blurry.toml` like this:

```toml
[blurry.template_schema_types]
ContextWebPage = "WebPage"
```
